apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: hzd454/nats-broadcaster:1.2.2
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
          resources:
            limits:
              memory: 150Mi
              cpu: 150m
